#!/bin/bash
set -euo pipefail

if [[ "${BUILDKITE_PLUGIN_ARTIFACTS_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "~~~ :hammer: Enabling debug mode"
  set -x
fi

args=()

if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_STEP:-}" ]] ; then
  args+=("--step" "${BUILDKITE_PLUGIN_ARTIFACTS_STEP}")
fi

if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_BUILD:-}" ]] ; then
  args+=("--build" "${BUILDKITE_PLUGIN_ARTIFACTS_BUILD}")
fi

paths=()

SINGULAR_DOWNLOAD_OBJECT="false"
RELOCATION="false"
MULTIPLE_DOWNLOADS="false"

if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD:-}" ]] || { [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_FROM:-}" ]] && [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO:-}" ]]; }; then
    SINGULAR_DOWNLOAD_OBJECT="true"
    if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD:-}" ]] ; then
      paths+=("$BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD")
    elif [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_FROM:-}" ]] && [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO:-}" ]] ; then
      RELOCATION="true"
      paths+=("$BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_FROM")
    fi
fi

while IFS='=' read -r path _ ; do
  if [[ $path =~ ^(BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_[0-9]+) ]] && ! [[ $path =~ ^(BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_[0-9]_TO+) ]]; then
    MULTIPLE_DOWNLOADS="true"
    paths+=("${!path}")
  fi
done < <(env | sort)

workdir="${BUILDKITE_PLUGIN_ARTIFACTS_WORKDIR:-.}"

if [[ "${SINGULAR_DOWNLOAD_OBJECT}" == "true" ]]; then
  if [[ "${RELOCATION}" == "true" ]]; then
    source="${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_FROM}"
  else
    source="${paths[*]}"
  fi

  if [[ "${#args[@]}" -gt 0 ]]; then
    echo "~~~ Downloading artifacts with args: ${args[*]}"
    buildkite-agent artifact download "${args[@]}" "${source}" "${workdir}"
  else
    echo "~~~ Downloading artifacts"
    buildkite-agent artifact download "${source}" "${workdir}"
  fi
  if [[ -n "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO:-}" ]]; then
    if ! [[ -d $(dirname "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO}") ]]; then
        mkdir -p "$(dirname "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO}")"
    fi
    # Handler for extract artifacts
    if [[ "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_EXTRACT:-false}" =~ ^(true|on|1)$ ]] ; then
      echo "~~~ Extracting [${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_FROM}] to [${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO}]..."
      mkdir -p ${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO}
      tar -xzf ${source} -C ${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO}
    else
      echo "~~~ Moving [${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_FROM}] to [${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO}]..."
      mv "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_FROM}" "${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO}"
    fi
  fi
elif [[ "${MULTIPLE_DOWNLOADS}" == "true" ]]; then
  index=0
  if [[ "${#args[@]}" -gt 0 ]]; then
    echo "~~~ Downloading artifacts with args: ${args[*]}"
    for path in "${paths[@]}"
      do
        source_env_var="BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_${index}_FROM"
        dest_env_var="BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_${index}_TO"
        extract_env_var="BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_${index}_EXTRACT"
        if [[ -n "${!source_env_var:-}" ]] && [[ -n "${!dest_env_var:-}" ]]; then
          source="${!source_env_var}"
        else
          source="${path}"
        fi
        buildkite-agent artifact download "${args[@]}" "${source}" "${workdir}"
        if [[ -n "${!dest_env_var:-}" ]]; then
          if ! [[ -d $(dirname "${!dest_env_var}") ]]; then
            mkdir -p "$(dirname "${!dest_env_var}")"
          fi
          # Handler for extract artifacts
          if [[ ${!extract_env_var:-false} =~ ^(true|on|1)$ ]] ; then
            echo "~~~ Extracting [${source}] to [${!dest_env_var}]..."
            mkdir -p ${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO}
            tar -xzf ${source} -C ${!dest_env_var}
          else
            echo "~~~ Moving [${source}] to [${!dest_env_var}]..."
            mv "${source}" "${!dest_env_var}"
          fi
        fi
        ((index+=1))
      done
  else
    echo "~~~ Downloading artifacts"

    for path in "${paths[@]}"
      do
        source_env_var="BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_${index}_FROM"
        dest_env_var="BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_${index}_TO"
        extract_env_var="BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_${index}_EXTRACT"
        if [[ -n "${!source_env_var:-}" ]] && [[ -n "${!dest_env_var:-}" ]]; then
          source="${!source_env_var}"
        else
          source="${path}"
        fi
        buildkite-agent artifact download "${source}" "${workdir}"
        if [[ -n "${!dest_env_var:-}" ]]; then
          if ! [[ -d $(dirname "${!dest_env_var}") ]]; then
            mkdir -p "$(dirname "${!dest_env_var}")"
          fi
          # Handler for extract artifacts
          if [[ ${!extract_env_var:-false} =~ ^(true|on|1)$ ]] ; then
            echo "~~~ Extracting [${source}] to [${!dest_env_var}]..."
            mkdir -p ${BUILDKITE_PLUGIN_ARTIFACTS_DOWNLOAD_TO}
            tar -xzf ${source} -C ${!dest_env_var}
          else
            echo "~~~ Moving [${source}] to [${!dest_env_var}]..."
            mv "${source}" "${!dest_env_var}"
          fi
        fi
        ((index+=1))
      done
  fi
fi
